Repository CraftsmenLtd/BloodConnect, pull requests merged in 2023-11, with the labels that each got.

#44 I-#4 basic config files added
  .eslintrc.json
  .nvmrc
  docs/development/GettingStarted.rst
  jest.config.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: chore

#49 I-#48 graphviz render
  .github/workflows/deploy-docs.yml
  docs/conf.py
Labels: bug

#50 I#43 Initial terraform setup with doc
  .gitignore
  Makefile
  docs/codes/terraform/variable.tf
  docs/development/index.rst
  docs/devops/IaC.rst
  docs/devops/index.rst
  docs/index.rst
  iac/terraform/aws/auth/data.tf
  iac/terraform/aws/auth/outputs.tf
  iac/terraform/aws/auth/variables.tf
  iac/terraform/aws/budget.tf
  iac/terraform/aws/data.tf
  iac/terraform/aws/iam_policy.tf
  iac/terraform/aws/local.tf
  iac/terraform/aws/modules.tf
  iac/terraform/aws/provider.tf
  iac/terraform/aws/variable.tf
Labels: devops
